
project_id = "ujyhmchmjzlmsimtrtor"

[functions.generate-proposal]
verify_jwt = true

[auth.email]
enable_signup = true
enable_confirmations = false

[auth]
debug = true
site_url = "https://ujyhmchmjzlmsimtrtor.supabase.co"
additional_redirect_urls = [
  "http://localhost:3000", 
  "http://localhost:5173", 
  "http://localhost:8080",
  "https://localhost:3000", 
  "https://localhost:5173",
  "https://localhost:8080",
  "https://localhost",
  "http://localhost",
  "https://ujyhmchmjzlmsimtrtor.supabase.co",
  "https://api.lovable.ai",
  "https://*.api.lovable.ai"
]
