
project_id = "ujyhmchmjzlmsimtrtor"

[functions.generate-proposal]
verify_jwt = true

[auth.email]
enable_signup = true
enable_confirmations = false

[auth]
debug = true
site_url = "https://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "https://localhost:5173"]
