
export const INDUSTRY_OPTIONS = [
  "Agriculture",
  "Automotive",
  "Banking & Finance",
  "Construction",
  "Consulting",
  "Education",
  "Entertainment",
  "Food & Beverage",
  "Government",
  "Healthcare",
  "Hospitality",
  "Information Technology",
  "Insurance",
  "Legal Services",
  "Manufacturing",
  "Marketing & Advertising",
  "Media & Publishing",
  "Mining & Metals",
  "Non-Profit",
  "Oil & Gas",
  "Pharmaceuticals",
  "Real Estate",
  "Retail",
  "Telecommunications",
  "Transportation & Logistics",
  "Travel & Tourism",
  "Utilities",
  "Wholesale Distribution",
  "Other"
];
