
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujyhmchmjzlmsimtrtor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqeWhtY2htanpsbXNpbXRydG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1OTY5MjgsImV4cCI6MjA1NjE3MjkyOH0.SC-lanLW6TQ6c3BWGPvxtjPpB5oufTvb8j-FmLFHGwI";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      flowType: 'pkce',
      debug: true // Keep debug mode on to help troubleshoot
    },
    global: {
      headers: {
        'x-client-info': `@supabase/js@${process.env.npm_package_dependencies_supabase_js || 'unknown'}`
      },
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);

// Add a helper function to check auth status without session detection issues
export const checkAuthStatus = async () => {
  try {
    const { data, error } = await supabase.auth.getSession();
    console.log("Auth status check:", data, error);
    return { data, error };
  } catch (e) {
    console.error("Auth status check failed:", e);
    return { data: null, error: e };
  }
};
